services:
  #account-management:
  #  build: .
  #  ports:
  #    - "8080:9091"
  #  working_dir: /app
  #  links:
  #    - db
  #  depends_on:
  #    - db

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"